project:
  type: book
  output-dir: _output

book:
  title: "中国科学院大学学位论文"
  chapters:
    - index.qmd
    - chapters/01-introduction.qmd
    - chapters/02-methods.qmd
    - chapters/03-conclusion.qmd
    - chapters/04-quina-example.qmd
    - references.qmd
    - appendices/appendix-a.qmd
    - backmatter.qmd

format:
  ucasthesis-pdf:
    keep-tex: true
  docx:
    toc: true
    number-sections: true
    bibliography: Biblio/ref.bib
    citeproc: true

execute:
  echo: false
  warning: false
  message: false
